# k8s/api-ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ai-reliability-standards-http
  namespace: ai-reliability-standards
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`aire.exosphere.host`)
      kind: Rule
      services:
        - name: ai-reliability-standards
          namespace: ai-reliability-standards
          port: 80